"""Ajout de la colonne email_sent

Revision ID: 4ddd51a5e0c7
Revises: 7e74af8d5448
Create Date: 2024-11-15 19:00:39.007445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddd51a5e0c7'
down_revision = '7e74af8d5448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
